.Dd September 23, 2022
.Dt BULKRENAME 1
.Os
.Sh NAME
.Nm bulkrename
.Nd edit filenames interactively within editor
.Sh SYNOPSIS
.Nm
.Op Ar file ...
.Sh DESCRIPTION
.Nm
receives filenames from its arguments (one per argument) or from stdin
(one per line) and opens an editor to edit them;
then, it renames each file to the corresponding edited one.
.Pp
If there are no arguments,
.Nm
operates on stdin,
reading one filename per line.
If there are arguments, each argument is read as a filename.
.Pp
The environment variables
.Ev EDITOR
and
.Ev VISUAL
are checked, in this order, for an editor program.
If both are unset, use
.Xr vi 1
by default.
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm Ns :
.Bl -tag -width Ds
.It Ev EDITOR
The editor to be used.
.It Ev VISUAL
The editor to be used if
.Ev EDITOR
is not set.
.El
.Sh EXAMPLES
Open editor to rename all
.Pa "*.jpg"
files:
.Bd -literal -offset indent
$ bulkrename *.jpg
.ED
.Sh SEE ALSO
.Xr vi 1
