#!/bin/sh
# bulkrename: bulk rename files using $EDITOR and temporary files
# this file in public domain

EDITOR="${EDITOR:-"${VISUAL:-"vi"}"}"

# create temporary files
if ! tmpfile="$(mktemp)"
then
	printf "bulkrename: could not make temporary file\n" >&2
	exit 1
fi
trap 'rm -f "$tmpfile"' EXIT

# if no argument is passed, fill $@ with lines from stdin
if [ $# -eq 0 ]
then                            # run on stdin
	while read -r line
	do
		set -- "$@" "$line"
	done
fi

# check if arguments are valid and write them to tmpfile
nargs="$#"
for arg
do
	case "$arg" in
	("")
		printf "bulkrename: empty argument\n" >&2
		exit 1
		;;
	(*[[:cntrl:]]*)
		printf "bulkrename: control characters in filenames are not supported\n" >&2
		exit 1
		;;
	([[:space:]]*|*[[:space:]])
		printf "bulkrename: filenames beginning or ending in space is not supported\n" >&2
		exit 1
		;;
	esac
	if ! test -e "$arg"
	then
		printf "bulkrename: %s: file does not exist\n" "$arg" >&2
		exit 1
	fi
	printf "%s\n" "$arg" >> "$tmpfile"
done

# call editor on tmpfile
"$EDITOR" -- "$tmpfile" </dev/tty

# read new filenames from edited tmpfile
while read -r target && test "$nargs" -gt 0
do
	source="$1"

	# for each target filename read from the file there is a
	# corresponding entry in $@.  We read filenames from the
	# file up to $nargs, and append $@ with commands:
	# "rm" "file"           (remove file)
	# "mv0" "from" "to"     (move file on the next loop)
	# "mv1" "from" "to"     (move file on the last loop)
	if test -z "$target"
	then
		# line asks to remove file
		set -- "$@" "rm" "$source"
	elif test "$target" = "$source"
	then
		# line does nothing
		:
	elif for arg ; do test "${i:-0}" -lt "$nargs" && test "$target" = "$arg" && break ; done
	then
		# line renaming creates filename collision; get unique filename
		unique="$source"
		while test -e "$unique"
		do
			unique="$unique~"
		done
		set -- "$@" "mv0" "$source" "$unique"
		set -- "$@" "mv1"  "$unique" "$target"
		i="$((i+1))"
	else
		# line is a renaming without collision
		set -- "$@" "mv0" "$source" "$target"
	fi

	# we're done with this source file
	shift
	nargs="$((nargs - 1))"
done <"$tmpfile"
shift "$nargs"

# perform the commands specified in the argument list
while test "$#" -gt 0
do
	case "$1" in
	("rm")
		rm -- "$2"
		printf "rm %s\n" "$2"
		shift 2
		;;
	("mv0")
		mv -- "$2" "$3"
		printf "%s -> %s\n" "$2" "$3"
		shift 3
		;;
	("mv1")
		set -- "$@" "mv2" "$2" "$3"
		shift 3
		;;
	("mv2")
		break
		;;
	(*)
		printf "bulkrename: unknown command %s\n" "$1" >&2
		exit 1
		;;
	esac
done

# perform the commands specified in the argument list (the final ones)
while test "$#" -gt 0
do
	case "$1" in
	("mv2")
		mv -- "$2" "$3"
		printf "%s -> %s\n" "$2" "$3"
		shift 3
		;;
	(*)
		printf "bulkrename: unknown command %s\n" "$1" >&2
		exit 1
		;;
	esac
done
