#!/bin/sh
# pick: select arguments
# this file in public domain

quoting_style="${QUOTING_STYLE:-"literal"}"
delimiter='
'

usage() {
	echo "usage: pick [-bnq] [-d delimiter] arg..." >&2
	exit 1
}

pick() {
	# print prompt to terminal and read response from terminal
	printf "%s? " "$1" >/dev/tty
	read -r response </dev/tty
	case "$response" in
	y*|s*)
		if [ "$quoting_style" = "escape" ]
		then
			printf "%s" "$1" | sed "s/\\([ 	]\\)/\\\\\\1/g; s/'/\\\\'/g"
		elif [ "$quoting_style" = "shell" ]
		then
			printf "'"
			printf "%s" "$1" | sed "s/'/'\\\\''/g"
			printf "'"
		else
			printf "%s" "$1" | sed "s/'/\\\\'/g"
		fi
		printf "%s" "$delimiter"
		;;
	q*)
		exit 0
		;;
	esac
}

while getopts 'bd:qn' c
do
	case "$c" in
	b)
		quoting_style="escape"
		;;
	d)
		delimiter="$OPTARG"
		;;
	q)
		quoting_style="shell"
		;;
	n)
		delimiter=" "
		;;
	*)
		usage
		;;
	esac
done
shift $((OPTIND -1))

if test "$#" -eq 0
then
	usage
elif test "$#" -eq 1 && test "$1" = '-'
then
	while read -r arg
	do
		pick "$arg"
	done
else
	for arg
	do
		pick "$arg"
	done
fi
