.Dd September 26, 2022
.Dt SKEL 1
.Os
.Sh NAME
.Nm skel
.Nd create a template file in the current directory
.Sh SYNOPSIS
.Nm
.Op Ar template Op Ar name
.Sh DESCRIPTION
.Nm
copies the specified skeleton file from the skeleton directory into the current directory.
A skeleton file is a template file containing a sample of a file format.
.Pp
If
.Nm
receives no argument, it only lists the available skeleton files.
If it receives argument, copies the
.Ar template
skeleton file into the current directory by the name
.Ar name .
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm
.Bl -tag -width Ds
.It Ev SKEL
The directory containing skeleton files.
If not specified, use
.Pa ~/.local/share/skel
by default.
.El
.Sh FILES
.Bl -tag -width Ds
.Pa $SKEL/*
Skeleton files.
