#!/bin/sh
# skel - create a template file in the current directory
# this file in public domain

SKEL="${SKEL:-"${XDG_DATA_HOME:-"$HOME/.local/share"}/skel"}"

usage() {
	echo "usage: skel [template [name]]" >&2
	exit 1
}

listskel() {
	ls -1 "$SKEL"
	return 0
}

createskel() {
	skelfile="${SKEL}/$1"
	destfile="${PWD}/$2"

	if [ ! -e "$skelfile" ]
	then
		printf "skel: %s: skeleton file does not exist\n" "$1" >&2
		exit 1
	fi

	if [ -e "$destfile" ]
	then
		printf "skel: %s: destination file already exists\n" "$2" >&2
		exit 1
	else
		echo cp -R -- "$skelfile" "$destfile"
		cp -R -- "$skelfile" "$destfile"
	fi
}

case $# in
0)
	listskel
	;;
1)
	createskel "$1" "$1"
	;;
2)
	createskel "$1" "$2"
	;;
*)
	usage
	;;
esac

exit 0
