.TH unpack 1
.SH NAME
unpack \- unarchive archive files
.SH SYNOPSIS
.B unpack
.I file
.RI [ directory ]
.SH DESCRIPTION
.B unpack
extracts the contents of an archive file such as .zip or .tar.gz in the
current directory or in the specified directory
.PP
The mimetypes of the supported archive file formats are the following:
.IP
application/gzip (.tar.gz)
.IP
application/x-tar (.tar)
.IP
application/zip (.zip)
.IP
application/vnd.rar (.rar)
.IP
application/x-7z-compressed (.7z)
.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B >0
Error occurred.
.SH EXAMPLES
Extract the content of file.zip into the home directory.
.IP
.EX
$ unpack file.zip $HOME
.EE
.SH SEE ALSO
.IR tar (1),
.IR gzip (1),
.IR unzip (1),
.IR unrar (1),
.IR 7z (1)
