#!/bin/sh
# unpack - unarchive archive files
# this file in public domain

err()
{
	printf 'unpack: %s\n' "$1" >&2
	exit 1
}

usage()
{
	echo "usage: unpack file [destdir]" >&2
	exit 1
}

case "$#" in
(1) set -- "$1" "$PWD" ;;
(2)                    ;;
(*) usage              ;;
esac

test -f "$1" || err "$1: not a regular file"
test -d "$2" || err "$2: not a regular directory"

case "$(file -ib -- "$1" | cut -d';' -f1 | cut -d'/' -f2)" in
gzip|x-gzip)
	tar xzvf "$1" -C "$2" >/dev/null || err "extraction failed"
	;;
bzip2|x-bzip2)
	tar xjvf "$1" -C "$2" >/dev/null || err "extraction failed"
	;;
tar|x-tar)
	tar xvf "$1" -C "$2" >/dev/null || err "extraction failed"
	;;
zip)
	unzip -d "$2" -- "$1" >/dev/null || err "extraction failed"
	;;
x-rar)
	unrar x "$1" "$2" >/dev/null || err "extraction failed"
	;;
x-7z-compressed)
	7z x -o"$2" "$1" >/dev/null || err "extraction failed"
	;;
x-xz)
	xzcat "$1" | tar xvf - -C "$2" >/dev/null || err "extraction failed"
	;;
*)
	err "%s: unknown archive file"
	;;
esac

printf "%s -> %s\n" "$1" "$2"
